### ISSUE TITLE
Proposal to integrate work: Hierarchical Diffusion for Offline Decision Making

### ISSUE THREAD

**Issue by CeHao-NUS** [CleanDiffuserTeam/CleanDiffuser#3]
Hi, thanks for the code base.

I recommend to integrate two works in the future versions.
1. Hierarchical Diffusion for Offline Decision Making (https://openreview.net/pdf?id=55kLa7tH9o)
2. Simple Hierarchical Planning with Diffusion (https://arxiv.org/html/2401.02644v1)

Thanks a lot!

**Comment by ZibinDong** [comment]
Thank you very much for your interest and your proposal. We aim to develop CleanDiffuser into a convenient library for building diffusion decision-making algorithms. Therefore, the algorithms implemented in ``/pipelines`` are actually demonstrations of CleanDiffuser's usage, rather than the main focus. 
Currently, our efforts are focused on writing documentation and tutorials (as you may have noticed, these parts are still incomplete), and we may not have the extra resources to integrate these two algorithms into CleanDiffuser. Perhaps in future versions, after the main tasks are completed, we will incorporate these two excellent diffusion planners. 
Thank you again for your interest.
