### ISSUE TITLE
A problem for requirements installation.

### ISSUE THREAD

**Issue by CeHao-NUS** [CleanDiffuserTeam/CleanDiffuser#4]
I faced a problem when install requirements.
It seems the numba and robosuite versions are in conflict. 

Using cached numba-0.56.0-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.5 MB)
ERROR: Cannot install -r requirements.txt (line 24) and numba==0.56.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numba==0.56.0
    robosuite 1.2.0 depends on numba<=0.53.1 and >=0.52.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by pickxiguapi** [comment]
This is mainly due to the fact that we are trying to work around all the IL and RL environment dependencies using a single `requirements.txt`, resulting in compatibility errors. We are modifying and testing the new installation tutorial now like [#2](https://github.com/CleanDiffuserTeam/CleanDiffuser/issues/2) mentioned.

**Comment by pickxiguapi** [comment]
Hi, we have fixed the environment incompatibility issue in the latest commit and provided a more user-friendly installation tutorial.  I'll close this issue, feel free to re-open it if there are more issues!
